# Generated by Django 4.2.22 on 2025-09-15 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('constituents', '0016_constituentgroup_registrant_members_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('cooperative_type', models.CharField(choices=[('Agricultural', 'Agricultural'), ('Consumer', 'Consumer'), ('Credit', 'Credit'), ('Housing', 'Housing'), ('Transport', 'Transport'), ('Fishery', 'Fishery'), ('Other', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Inactive', 'Inactive'), ('Dissolved', 'Dissolved')], default='Pending', max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('barangay', models.CharField(max_length=100)),
                ('municipality', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_established', models.DateField()),
                ('date_registered', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_members', models.PositiveIntegerField(default=0)),
                ('registration_certificate', models.FileField(blank=True, null=True, upload_to='cooperatives/documents/')),
                ('articles_of_cooperation', models.FileField(blank=True, null=True, upload_to='cooperatives/documents/')),
                ('bylaws', models.FileField(blank=True, null=True, upload_to='cooperatives/documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_cooperatives', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CooperativeMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('Secretary', 'Secretary'), ('Treasurer', 'Treasurer'), ('Board Member', 'Board Member'), ('Regular Member', 'Regular Member'), ('Committee Chair', 'Committee Chair'), ('Committee Member', 'Committee Member')], max_length=50)),
                ('date_joined', models.DateField()),
                ('date_appointed', models.DateField(blank=True, null=True)),
                ('term_start', models.DateField(blank=True, null=True)),
                ('term_end', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_founding_member', models.BooleanField(default=False)),
                ('membership_number', models.CharField(blank=True, max_length=50, null=True)),
                ('shares_owned', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='cooperatives.cooperative')),
                ('fahaniecares_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooperative_memberships', to='constituents.fahaniecaresmember')),
            ],
            options={
                'unique_together': {('cooperative', 'fahaniecares_member', 'position')},
            },
        ),
    ]
