# Generated by Django 4.2.22 on 2025-09-17 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constituents', '0016_constituentgroup_registrant_members_and_more'),
        ('cooperatives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CooperativeOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('Secretary', 'Secretary'), ('Treasurer', 'Treasurer'), ('Board Member', 'Board Member'), ('Regular Member', 'Regular Member'), ('Committee Chair', 'Committee Chair'), ('Committee Member', 'Committee Member')], max_length=50)),
                ('date_joined', models.DateField()),
                ('date_appointed', models.DateField(blank=True, null=True)),
                ('term_start', models.DateField(blank=True, null=True)),
                ('term_end', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officers', to='cooperatives.cooperative')),
                ('fahaniecares_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooperative_officer_positions', to='constituents.fahaniecaresmember')),
            ],
            options={
                'unique_together': {('cooperative', 'fahaniecares_member', 'position')},
            },
        ),
    ]
