# Generated by Django 4.2.7 on 2025-05-27 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full name as it appears in Notion', max_length=255)),
                ('position', models.CharField(blank=True, help_text='Position/Designation', max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('division', models.CharField(blank=True, choices=[('legislative_affairs', 'Legislative Affairs'), ('administrative_affairs', 'Administrative Affairs'), ('communications', 'Communications'), ('mp_office', "MP Uy-Oyod's Office"), ('it_unit', 'IT Unit')], max_length=30)),
                ('office', models.CharField(blank=True, choices=[('main_office', 'Main Office'), ('satellite_office', 'Satellite Office')], max_length=20)),
                ('employment_status', models.CharField(blank=True, choices=[('coterminous', 'Coterminous'), ('contractual', 'Contractual'), ('consultant', 'Consultant'), ('intern', 'Intern'), ('volunteer', 'Volunteer')], max_length=20)),
                ('date_hired', models.DateField(blank=True, help_text='Date Hired/Engaged', null=True)),
                ('duties_responsibilities', models.TextField(blank=True)),
                ('staff_workflow', models.TextField(blank=True, help_text='Daily workflow and tasks')),
                ('is_active', models.BooleanField(default=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='staff_profiles/')),
                ('bio', models.TextField(blank=True)),
                ('notion_id', models.CharField(blank=True, help_text='Notion page ID for this staff member', max_length=36, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, help_text='Associated user account (optional for external staff)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Member',
                'verbose_name_plural': 'Staff Members',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='StaffTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('division', models.CharField(blank=True, choices=[('legislative_affairs', 'Legislative Affairs'), ('administrative_affairs', 'Administrative Affairs'), ('communications', 'Communications'), ('mp_office', "MP Uy-Oyod's Office"), ('it_unit', 'IT Unit')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(blank=True, related_name='teams', to='staff.staff')),
                ('team_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_teams', to='staff.staff')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StaffSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisors', to='staff.staff')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervised_staff', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Staff Supervisor Relationship',
                'verbose_name_plural': 'Staff Supervisor Relationships',
                'unique_together': {('staff', 'supervisor')},
            },
        ),
        migrations.CreateModel(
            name='StaffPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_period', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-Annual'), ('annual', 'Annual')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('overall_rating', models.PositiveSmallIntegerField(choices=[(5, 'Outstanding'), (4, 'Very Good'), (3, 'Good'), (2, 'Needs Improvement'), (1, 'Poor')])),
                ('quality_of_work', models.PositiveSmallIntegerField(blank=True, choices=[(5, 'Outstanding'), (4, 'Very Good'), (3, 'Good'), (2, 'Needs Improvement'), (1, 'Poor')], null=True)),
                ('punctuality', models.PositiveSmallIntegerField(blank=True, choices=[(5, 'Outstanding'), (4, 'Very Good'), (3, 'Good'), (2, 'Needs Improvement'), (1, 'Poor')], null=True)),
                ('teamwork', models.PositiveSmallIntegerField(blank=True, choices=[(5, 'Outstanding'), (4, 'Very Good'), (3, 'Good'), (2, 'Needs Improvement'), (1, 'Poor')], null=True)),
                ('communication', models.PositiveSmallIntegerField(blank=True, choices=[(5, 'Outstanding'), (4, 'Very Good'), (3, 'Good'), (2, 'Needs Improvement'), (1, 'Poor')], null=True)),
                ('initiative', models.PositiveSmallIntegerField(blank=True, choices=[(5, 'Outstanding'), (4, 'Very Good'), (3, 'Good'), (2, 'Needs Improvement'), (1, 'Poor')], null=True)),
                ('strengths', models.TextField(blank=True)),
                ('areas_for_improvement', models.TextField(blank=True)),
                ('goals_next_period', models.TextField(blank=True)),
                ('evaluator_comments', models.TextField(blank=True)),
                ('evaluation_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_evaluations', to='staff.staff')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to='staff.staff')),
            ],
            options={
                'ordering': ['-evaluation_date'],
                'unique_together': {('staff', 'evaluation_period', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_in', models.TimeField(blank=True, null=True)),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('sick_leave', 'Sick Leave'), ('vacation_leave', 'Vacation Leave'), ('official_business', 'Official Business'), ('holiday', 'Holiday')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_attendance', to='staff.staff')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='staff.staff')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('staff', 'date')},
            },
        ),
    ]
