# Generated by Django 4.2.7 on 2025-06-06 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staff_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffWorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('division', models.CharField(blank=True, choices=[('legislative_affairs', 'Legislative Affairs'), ('administrative_affairs', 'Administrative Affairs'), ('communications', 'Communications'), ('mp_office', "MP Uy-Oyod's Office"), ('it_unit', 'IT Unit')], max_length=30)),
                ('position', models.CharField(blank=True, help_text='Specific position this applies to', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_assign', models.BooleanField(default=False, help_text='Automatically assign to matching staff')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Task title or summary', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed task description')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('due_date', models.DateTimeField(blank=True, help_text='Task deadline', null=True)),
                ('start_date', models.DateTimeField(blank=True, help_text='When task should start', null=True)),
                ('completed_date', models.DateTimeField(blank=True, help_text='When task was completed', null=True)),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated hours to complete', max_digits=5, null=True)),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Actual hours spent on task', max_digits=5, null=True)),
                ('progress_percentage', models.PositiveSmallIntegerField(default=0, help_text='Progress percentage (0-100)')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or updates')),
                ('attachments', models.FileField(blank=True, help_text='Task-related files', null=True, upload_to='task_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Staff member who assigned this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to='staff.staff')),
                ('assigned_to', models.ForeignKey(help_text='Staff member assigned to this task', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='staff.staff')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color code for category', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Task Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Order within workflow')),
                ('depends_on_previous', models.BooleanField(default=False, help_text='Must wait for previous task')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.taskcategory')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_tasks', to='staff.staffworkflowtemplate')),
            ],
            options={
                'ordering': ['workflow', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TaskTimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(help_text='When work started')),
                ('end_time', models.DateTimeField(blank=True, help_text='When work ended', null=True)),
                ('duration_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Duration in hours (calculated automatically)', max_digits=5, null=True)),
                ('description', models.TextField(blank=True, help_text='What was worked on during this time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='staff.staff')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='staff.task')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text='Comment or update text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_comments', to='staff.staff')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='staff.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='staff.taskcategory'),
        ),
        migrations.AddField(
            model_name='task',
            name='depends_on',
            field=models.ManyToManyField(blank=True, help_text='Tasks that must be completed before this one', related_name='dependent_tasks', to='staff.task'),
        ),
    ]
