# Generated by Django 4.2.7 on 2025-06-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_staffworkflowtemplate_task_taskcategory_workflowtask_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='notion_id',
            field=models.CharField(blank=True, help_text='Notion page ID for this staff member', max_length=36, null=True, unique=True),
        ),
    ]
