# Generated by Django 4.2.7 on 2025-06-07 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_fix_notion_id_unique_constraint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='notion_id',
        ),
    ]
