# Generated by Django 4.2.7 on 2025-06-06 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_middle_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable permission name', max_length=255, unique=True)),
                ('codename', models.CharField(help_text='Programmatic permission identifier', max_length=100, unique=True)),
                ('description', models.TextField(help_text='Detailed description of what this permission allows')),
                ('module', models.CharField(help_text='Module this permission belongs to', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['module', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('mp', 'Member of Parliament'), ('chief_of_staff', 'Chief of Staff'), ('admin', 'System Administrator'), ('coordinator', 'Coordinator'), ('info_officer', 'Information Officer'), ('chapter_member', 'Chapter Member'), ('registered_user', 'Registered User'), ('constituent', 'Constituent'), ('member', 'Member'), ('staff', 'Parliamentary Office Staff')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('can_delegate', models.BooleanField(default=False, help_text='Can this role delegate this permission to others?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['role', 'permission__module', 'permission__name'],
            },
        ),
        migrations.CreateModel(
            name='RoleTransitionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_role', models.CharField(blank=True, choices=[('mp', 'Member of Parliament'), ('chief_of_staff', 'Chief of Staff'), ('admin', 'System Administrator'), ('coordinator', 'Coordinator'), ('info_officer', 'Information Officer'), ('chapter_member', 'Chapter Member'), ('registered_user', 'Registered User'), ('constituent', 'Constituent'), ('member', 'Member'), ('staff', 'Parliamentary Office Staff')], max_length=20, null=True)),
                ('to_role', models.CharField(choices=[('mp', 'Member of Parliament'), ('chief_of_staff', 'Chief of Staff'), ('admin', 'System Administrator'), ('coordinator', 'Coordinator'), ('info_officer', 'Information Officer'), ('chapter_member', 'Chapter Member'), ('registered_user', 'Registered User'), ('constituent', 'Constituent'), ('member', 'Member'), ('staff', 'Parliamentary Office Staff')], max_length=20)),
                ('reason', models.TextField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPermissionOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_granted', models.BooleanField(default=True, help_text='True to grant, False to revoke')),
                ('reason', models.TextField(help_text='Reason for this override')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this override expires', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='last_permission_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role_assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('mp', 'Member of Parliament'), ('chief_of_staff', 'Chief of Staff'), ('admin', 'System Administrator'), ('coordinator', 'Coordinator'), ('info_officer', 'Information Officer'), ('chapter_member', 'Chapter Member'), ('registered_user', 'Registered User'), ('constituent', 'Constituent'), ('member', 'Member'), ('staff', 'Parliamentary Office Staff')], default='registered_user', max_length=20),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_type'], name='users_user_user_ty_4573bb_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['chapter_id'], name='users_user_chapter_0bdc31_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_approved'], name='users_user_is_appr_0a895a_idx'),
        ),
        migrations.AddField(
            model_name='userpermissionoverride',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_overrides_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpermissionoverride',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.dynamicpermission'),
        ),
        migrations.AddField(
            model_name='userpermissionoverride',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roletransitionlog',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_changes_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roletransitionlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_transitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.dynamicpermission'),
        ),
        migrations.AddIndex(
            model_name='dynamicpermission',
            index=models.Index(fields=['codename'], name='users_dynam_codenam_f783ea_idx'),
        ),
        migrations.AddIndex(
            model_name='dynamicpermission',
            index=models.Index(fields=['module'], name='users_dynam_module_cb6eb8_idx'),
        ),
        migrations.AddIndex(
            model_name='dynamicpermission',
            index=models.Index(fields=['is_active'], name='users_dynam_is_acti_87a28d_idx'),
        ),
        migrations.AddIndex(
            model_name='userpermissionoverride',
            index=models.Index(fields=['user', 'is_granted'], name='users_userp_user_id_bdbccd_idx'),
        ),
        migrations.AddIndex(
            model_name='userpermissionoverride',
            index=models.Index(fields=['expires_at'], name='users_userp_expires_5d84fb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userpermissionoverride',
            unique_together={('user', 'permission')},
        ),
        migrations.AddIndex(
            model_name='roletransitionlog',
            index=models.Index(fields=['user', '-changed_at'], name='users_rolet_user_id_b5e660_idx'),
        ),
        migrations.AddIndex(
            model_name='roletransitionlog',
            index=models.Index(fields=['changed_by', '-changed_at'], name='users_rolet_changed_78e030_idx'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['role', 'is_active'], name='users_rolep_role_b87b44_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission')},
        ),
    ]
