# Generated by Django 4.2.7 on 2025-06-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_dynamicpermission_rolepermission_roletransitionlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('mp', 'Member of Parliament'), ('chief_of_staff', 'Chief of Staff'), ('staff', 'Parliamentary Office Staff'), ('admin', 'System Administrator'), ('coordinator', 'Coordinator'), ('info_officer', 'Information Officer'), ('chapter_member', 'Chapter Member'), ('registered_user', 'Registered User'), ('constituent', 'Constituent'), ('member', 'Member')], max_length=20),
        ),
        migrations.AlterField(
            model_name='roletransitionlog',
            name='from_role',
            field=models.CharField(blank=True, choices=[('superuser', 'Superuser'), ('mp', 'Member of Parliament'), ('chief_of_staff', 'Chief of Staff'), ('staff', 'Parliamentary Office Staff'), ('admin', 'System Administrator'), ('coordinator', 'Coordinator'), ('info_officer', 'Information Officer'), ('chapter_member', 'Chapter Member'), ('registered_user', 'Registered User'), ('constituent', 'Constituent'), ('member', 'Member')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='roletransitionlog',
            name='to_role',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('mp', 'Member of Parliament'), ('chief_of_staff', 'Chief of Staff'), ('staff', 'Parliamentary Office Staff'), ('admin', 'System Administrator'), ('coordinator', 'Coordinator'), ('info_officer', 'Information Officer'), ('chapter_member', 'Chapter Member'), ('registered_user', 'Registered User'), ('constituent', 'Constituent'), ('member', 'Member')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('mp', 'Member of Parliament'), ('chief_of_staff', 'Chief of Staff'), ('staff', 'Parliamentary Office Staff'), ('admin', 'System Administrator'), ('coordinator', 'Coordinator'), ('info_officer', 'Information Officer'), ('chapter_member', 'Chapter Member'), ('registered_user', 'Registered User'), ('constituent', 'Constituent'), ('member', 'Member')], default='registered_user', max_length=20),
        ),
    ]
