# Generated by Django 4.2.7 on 2025-06-07 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_superuser_staff_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='notion_id',
        ),
    ]
