# Generated by Django 4.2.7 on 2025-06-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_notion_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mfa_method',
            field=models.CharField(choices=[('totp', 'Authenticator App (TOTP)'), ('sms', 'SMS/Text Message')], default='totp', help_text='Preferred MFA method', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False, help_text='Is phone number verified for SMS OTP'),
        ),
        migrations.AddField(
            model_name='user',
            name='sms_otp_expires',
            field=models.DateTimeField(blank=True, help_text='SMS OTP expiration time', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sms_otp_secret',
            field=models.CharField(blank=True, help_text='Temporary SMS OTP', max_length=6),
        ),
    ]
