# Generated by Django 4.2 on 2025-05-18 04:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('acronym', models.CharField(blank=True, max_length=20)),
                ('committee_type', models.CharField(choices=[('standing', 'Standing Committee'), ('special', 'Special Committee'), ('joint', 'Joint Committee'), ('subcommittee', 'Subcommittee'), ('adhoc', 'Ad Hoc Committee')], max_length=20)),
                ('jurisdiction', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('established_date', models.DateField()),
                ('dissolved_date', models.DateField(blank=True, null=True)),
                ('chairperson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chaired_committees', to=settings.AUTH_USER_MODEL)),
                ('parent_committee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcommittees', to='parliamentary.committee')),
                ('vice_chairperson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vice_chaired_committees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LegislativeMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure_type', models.CharField(choices=[('bill', 'House Bill'), ('resolution', 'House Resolution'), ('concurrent', 'Concurrent Resolution'), ('joint', 'Joint Resolution'), ('ordinance', 'Local Ordinance')], max_length=20)),
                ('number', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('short_title', models.CharField(blank=True, max_length=200)),
                ('abstract', models.TextField()),
                ('full_text_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('filed', 'Filed'), ('committee', 'In Committee'), ('plenary', 'Plenary Deliberation'), ('approved_house', 'Approved on Third Reading'), ('transmitted', 'Transmitted to Senate'), ('bicameral', 'Bicameral Conference'), ('enrolled', 'Enrolled'), ('enacted', 'Enacted into Law'), ('vetoed', 'Vetoed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High Priority'), ('normal', 'Normal'), ('low', 'Low Priority')], default='normal', max_length=10)),
                ('filed_date', models.DateField(blank=True, null=True)),
                ('last_action_date', models.DateField(blank=True, null=True)),
                ('primary_committee', models.CharField(blank=True, max_length=200)),
                ('secondary_committees', models.TextField(blank=True, help_text='Comma-separated list')),
                ('beneficiaries', models.TextField(blank=True, help_text='Target beneficiaries')),
                ('estimated_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('implementation_timeline', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=True)),
                ('co_authors', models.ManyToManyField(blank=True, related_name='co_authored_measures', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_measures', to=settings.AUTH_USER_MODEL)),
                ('principal_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='principal_measures', to=settings.AUTH_USER_MODEL)),
                ('related_measures', models.ManyToManyField(blank=True, to='parliamentary.legislativemeasure')),
            ],
            options={
                'ordering': ['-filed_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LegislativeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.CharField(max_length=50)),
                ('congress_number', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-start_date'],
                'unique_together': {('congress_number', 'session_number')},
            },
        ),
        migrations.CreateModel(
            name='PlenarySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('regular', 'Regular Session'), ('special', 'Special Session'), ('joint', 'Joint Session')], max_length=20)),
                ('session_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('order_of_business_url', models.URLField(blank=True)),
                ('journal_url', models.URLField(blank=True)),
                ('transcript_url', models.URLField(blank=True)),
                ('present_count', models.IntegerField(blank=True, null=True)),
                ('absent_count', models.IntegerField(blank=True, null=True)),
                ('key_events', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plenary_sessions', to='parliamentary.legislativesession')),
            ],
            options={
                'ordering': ['-session_date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='SpeechPrivilege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speech_type', models.CharField(choices=[('privilege_personal', 'Privilege Speech - Personal'), ('privilege_collective', 'Privilege Speech - Collective'), ('manifestation', 'Manifestation'), ('sponsorship', 'Sponsorship Speech'), ('interpellation', 'Interpellation'), ('explanation', 'Explanation of Vote')], max_length=30)),
                ('title', models.CharField(max_length=300)),
                ('summary', models.TextField()),
                ('full_text_url', models.URLField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('start_time', models.TimeField()),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plenary_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speeches', to='parliamentary.plenarysession')),
                ('related_measure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speeches', to='parliamentary.legislativemeasure')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speeches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['plenary_session', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='OversightActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('activity_type', models.CharField(choices=[('investigation', 'Investigation'), ('monitoring', 'Monitoring'), ('audit', 'Audit Review'), ('inspection', 'Site Inspection'), ('inquiry', 'Inquiry'), ('hearing', 'Oversight Hearing')], max_length=20)),
                ('description', models.TextField()),
                ('target_agency', models.CharField(max_length=200)),
                ('target_program', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('key_findings', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('report_url', models.URLField(blank=True)),
                ('presentation_url', models.URLField(blank=True)),
                ('requires_followup', models.BooleanField(default=False)),
                ('followup_deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('committee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oversight_activities', to='parliamentary.committee')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_oversight', to=settings.AUTH_USER_MODEL)),
                ('lead_member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_oversight', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Oversight activities',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='legislativemeasure',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measures', to='parliamentary.legislativesession'),
        ),
        migrations.AddField(
            model_name='legislativemeasure',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='parliamentary.legislativemeasure'),
        ),
        migrations.CreateModel(
            name='LegislativeAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('filed', 'Filed'), ('referred', 'Referred to Committee'), ('hearing', 'Committee Hearing'), ('approved_committee', 'Approved in Committee'), ('reported_out', 'Reported Out'), ('calendared', 'Calendared for Plenary'), ('plenary_debate', 'Plenary Debate'), ('vote', 'Voted On'), ('approved', 'Approved'), ('transmitted', 'Transmitted'), ('conference', 'Bicameral Conference'), ('enrolled', 'Enrolled'), ('signed', 'Signed into Law'), ('vetoed', 'Vetoed')], max_length=20)),
                ('action_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('vote_yes', models.IntegerField(blank=True, null=True)),
                ('vote_no', models.IntegerField(blank=True, null=True)),
                ('vote_abstain', models.IntegerField(blank=True, null=True)),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='parliamentary.legislativemeasure')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-action_date'],
            },
        ),
        migrations.CreateModel(
            name='CommitteeHearing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hearing_type', models.CharField(choices=[('regular', 'Regular Meeting'), ('special', 'Special Meeting'), ('public', 'Public Hearing'), ('executive', 'Executive Session'), ('markup', 'Markup Session')], max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('scheduled_date', models.DateTimeField()),
                ('actual_date', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=200)),
                ('agenda_url', models.URLField(blank=True)),
                ('minutes_url', models.URLField(blank=True)),
                ('recording_url', models.URLField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('attendance_count', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearings', to='parliamentary.committee')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hearings', to=settings.AUTH_USER_MODEL)),
                ('measures', models.ManyToManyField(blank=True, related_name='hearings', to='parliamentary.legislativemeasure')),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='VotingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('abstain', 'Abstain'), ('absent', 'Absent')], max_length=10)),
                ('reasoning', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='parliamentary.legislativemeasure')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_records', to=settings.AUTH_USER_MODEL)),
                ('voting_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='parliamentary.plenarysession')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('measure', 'member', 'voting_session')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='legislativemeasure',
            unique_together={('session', 'measure_type', 'number')},
        ),
        migrations.CreateModel(
            name='CommitteeMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('chairperson', 'Chairperson'), ('vice_chair', 'Vice Chairperson'), ('secretary', 'Secretary'), ('member', 'Member'), ('ex_officio', 'Ex Officio')], default='member', max_length=20)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='parliamentary.committee')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['committee', 'role', 'member'],
                'unique_together': {('committee', 'member', 'start_date')},
            },
        ),
    ]
