# Generated by Django 4.2 on 2025-05-18 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('constituents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chapters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('target_all_constituents', models.BooleanField(default=False)),
                ('target_user_types', models.JSONField(blank=True, default=list)),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('attachments', models.FileField(blank=True, null=True, upload_to='campaign_attachments/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('sent_time', models.DateTimeField(blank=True, null=True)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('successful_sends', models.PositiveIntegerField(default=0)),
                ('failed_sends', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL)),
                ('custom_recipients', models.ManyToManyField(blank=True, related_name='campaign_custom_recipients', to=settings.AUTH_USER_MODEL)),
                ('target_chapters', models.ManyToManyField(blank=True, related_name='campaigns', to='chapters.chapter')),
                ('target_groups', models.ManyToManyField(blank=True, related_name='campaigns', to='constituents.constituentgroup')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('referral_status', 'Referral Status Change'), ('application_status', 'Application Status Change'), ('chapter_activity', 'Chapter Activity'), ('program_update', 'Program Update'), ('system', 'System Notification')], max_length=30)),
                ('event_object_id', models.CharField(max_length=50)),
                ('event_description', models.TextField()),
                ('channels', models.JSONField(default=list)),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('template_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('letter', 'Letter'), ('social', 'Social Media')], max_length=20)),
                ('category', models.CharField(choices=[('announcement', 'Announcement'), ('invitation', 'Event Invitation'), ('newsletter', 'Newsletter'), ('update', 'Program Update'), ('reminder', 'Reminder'), ('thank_you', 'Thank You'), ('birthday', 'Birthday Greeting'), ('holiday', 'Holiday Greeting'), ('emergency', 'Emergency Alert')], max_length=20)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('allow_marketing', models.BooleanField(default=True)),
                ('allow_newsletters', models.BooleanField(default=True)),
                ('allow_event_invites', models.BooleanField(default=True)),
                ('allow_program_updates', models.BooleanField(default=True)),
                ('referral_notifications', models.BooleanField(default=True)),
                ('application_notifications', models.BooleanField(default=True)),
                ('chapter_notifications', models.BooleanField(default=True)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('preferred_language', models.CharField(default='en', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='communication_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('in_app', 'In-App Message')], max_length=20)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communications.communicationcampaign')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='communicationcampaign',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communications.communicationtemplate'),
        ),
        migrations.CreateModel(
            name='AnnouncementPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('news', 'News'), ('event', 'Event'), ('update', 'Update'), ('alert', 'Alert'), ('achievement', 'Achievement')], max_length=20)),
                ('summary', models.TextField(help_text='Brief summary for listing pages')),
                ('content', models.TextField()),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='announcements/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False)),
                ('show_on_homepage', models.BooleanField(default=True)),
                ('target_all', models.BooleanField(default=True)),
                ('target_user_types', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_announcements', to=settings.AUTH_USER_MODEL)),
                ('target_chapters', models.ManyToManyField(blank=True, related_name='announcements', to='chapters.chapter')),
            ],
            options={
                'ordering': ['-published_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='eventnotification',
            index=models.Index(fields=['recipient', 'is_read', 'created_at'], name='communicati_recipie_8ea74b_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationmessage',
            index=models.Index(fields=['recipient', 'created_at'], name='communicati_recipie_e0f997_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationmessage',
            index=models.Index(fields=['campaign', 'status'], name='communicati_campaig_a28e8c_idx'),
        ),
    ]
