# Generated by Django 4.2.21 on 2025-06-04 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communications', '0002_contactformsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnershipSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('partnership_type', models.CharField(choices=[('ngo', 'NGO/Non-Profit Organization'), ('business', 'Business/Corporate'), ('government', 'Government Agency'), ('academic', 'Academic Institution'), ('community', 'Community Organization'), ('individual', 'Individual Partner'), ('other', 'Other')], max_length=20)),
                ('proposed_collaboration', models.TextField(help_text='Describe the proposed collaboration or partnership')),
                ('resources_offered', models.TextField(blank=True, help_text='What resources can you offer?', null=True)),
                ('expected_outcomes', models.TextField(blank=True, help_text='What outcomes do you expect from this partnership?', null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('on_hold', 'On Hold')], default='new', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this partnership', null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_partnerships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partnership Submission',
                'verbose_name_plural': 'Partnership Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='DonationSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=100)),
                ('donor_type', models.CharField(choices=[('individual', 'Individual'), ('organization', 'Organization'), ('business', 'Business')], default='individual', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('donation_type', models.CharField(choices=[('monetary', 'Monetary Donation'), ('goods', 'Goods/Materials'), ('services', 'Services'), ('volunteer_time', 'Volunteer Time'), ('equipment', 'Equipment'), ('other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='For monetary donations', max_digits=10, null=True)),
                ('description', models.TextField(help_text='Describe the donation or intended use')),
                ('frequency', models.CharField(choices=[('one_time', 'One-time'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], default='one_time', max_length=20)),
                ('preferred_program', models.CharField(blank=True, help_text='Specific program to support', max_length=200, null=True)),
                ('status', models.CharField(choices=[('inquiry', 'Inquiry'), ('pledged', 'Pledged'), ('received', 'Received'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='inquiry', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('receipt_issued', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this donation', null=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donation Submission',
                'verbose_name_plural': 'Donation Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
