# Generated by Django 4.2.7 on 2025-06-06 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_partnershipsubmission_donationsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('subscription_type', models.CharField(choices=[('general', 'General Updates'), ('parliamentary', 'Parliamentary Updates'), ('programs', 'Program Announcements'), ('events', 'Event Invitations'), ('all', 'All Communications')], default='all', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('unsubscribed', 'Unsubscribed'), ('bounced', 'Bounced'), ('pending', 'Pending Confirmation')], default='active', max_length=20)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('subscription_source', models.CharField(default='website', help_text='Where the subscription came from', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('verification_token', models.CharField(blank=True, max_length=64, null=True)),
                ('emails_sent', models.PositiveIntegerField(default=0)),
                ('emails_opened', models.PositiveIntegerField(default=0)),
                ('last_engagement', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Email Subscription',
                'verbose_name_plural': 'Email Subscriptions',
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
