# Generated by Django 4.2.7 on 2025-06-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_emailsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformsubmission',
            name='subject',
            field=models.CharField(choices=[('assistance', 'Request Assistance'), ('feedback', 'Provide Feedback'), ('volunteer', 'Volunteer Opportunities'), ('chapter', 'Chapter Inquiries'), ('tdif_inquiry', 'TDIF Project Inquiry'), ('ministry_program_inquiry', 'Ministry Program Inquiry'), ('other', 'Other')], max_length=30),
        ),
    ]
