# Generated by Django 4.2.22 on 2025-06-18 02:57

import apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.core.utils.safe_media_upload),
        ),
    ]
