# Generated by Django 4.2 on 2025-05-26 12:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('constituents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FahanieCaresMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_application', models.DateField(auto_now_add=True)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20)),
                ('address_barangay', models.CharField(max_length=100)),
                ('address_municipality', models.CharField(max_length=100)),
                ('address_province', models.CharField(default='Maguindanao del Sur', max_length=100)),
                ('voter_address_barangay', models.CharField(max_length=100)),
                ('voter_address_municipality', models.CharField(max_length=100)),
                ('voter_address_province', models.CharField(default='Maguindanao del Sur', max_length=100)),
                ('sector', models.CharField(choices=[('pwd_student', 'PWD College Students'), ('solo_parent', 'Solo Parents'), ('volunteer_teacher', 'Volunteer Teachers'), ('volunteer_health', 'Volunteer Health Workers'), ('special_needs', 'Children with Special Needs'), ('senior_citizen', 'Senior Citizens'), ('women_mothers', 'Women/Mothers and Children'), ('student_scholarship', 'Students in Need of Scholarships'), ('student_assistance', 'Students Requiring Educational Assistance')], max_length=50)),
                ('highest_education', models.CharField(choices=[('elementary', 'Elementary School'), ('high_school', 'High School'), ('vocational', 'Vocational/Technical School'), ('some_college', 'Some College'), ('bachelors', "Bachelor's Degree"), ('masters', "Master's Degree"), ('doctorate', 'Doctorate Degree/PhD'), ('other', 'Other')], max_length=20)),
                ('school_graduated', models.CharField(blank=True, max_length=255)),
                ('eligibility', models.CharField(choices=[('none', 'None'), ('let_passer', 'LET Passer'), ('csc_passer', 'CSC Passer'), ('both', 'Both LET and CSC Passer')], default='none', max_length=20)),
                ('is_volunteer_teacher', models.BooleanField(default=False)),
                ('volunteer_school', models.CharField(blank=True, max_length=255)),
                ('volunteer_service_length', models.CharField(blank=True, help_text="Length of service as volunteer teacher (e.g., '2 years', '6 months')", max_length=100)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('notion_id', models.CharField(blank=True, help_text='Notion database ID', max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_members', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fahanie_cares_member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '#FahanieCares Member',
                'verbose_name_plural': '#FahanieCares Members',
                'ordering': ['-date_of_application'],
            },
        ),
    ]
