# Generated by Django 4.2.7 on 2025-06-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constituents', '0002_fahaniecaresmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='fahaniecaresmember',
            name='voter_id_photo',
            field=models.ImageField(blank=True, help_text="Upload a clear photo of your Voter's Certificate or ID for verification.", null=True, upload_to='voter_id_photos/'),
        ),
    ]
