# Generated by Django 4.2.7 on 2025-06-07 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constituents', '0003_fahaniecaresmember_voter_id_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constituent',
            name='notion_id',
        ),
        migrations.RemoveField(
            model_name='constituentgroup',
            name='notion_id',
        ),
        migrations.RemoveField(
            model_name='constituentinteraction',
            name='notion_id',
        ),
        migrations.RemoveField(
            model_name='fahaniecaresmember',
            name='notion_id',
        ),
    ]
