# Generated by Django 4.2.7 on 2025-06-07 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chapters', '0004_remove_chapter_notion_id_and_more'),
        ('constituents', '0004_remove_constituent_notion_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fahaniecaresmember',
            name='assigned_chapter',
            field=models.ForeignKey(blank=True, help_text='Chapter assigned to this approved member', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_members', to='chapters.chapter'),
        ),
        migrations.AddField(
            model_name='fahaniecaresmember',
            name='chapter_assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_chapter_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fahaniecaresmember',
            name='chapter_assigned_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
