# Generated by Django 4.2.22 on 2025-06-18 02:57

import apps.constituents.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constituents', '0005_fahaniecaresmember_assigned_chapter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fahaniecaresmember',
            name='eligibility',
            field=models.CharField(choices=[('none', 'None'), ('board_passer', 'Board Passer'), ('csc_passer', 'CSC Passer'), ('both', 'Both Board and CSC Passer')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='fahaniecaresmember',
            name='highest_education',
            field=models.CharField(choices=[('elementary', 'Elementary level'), ('high_school', 'High School level'), ('vocational', 'Vocational/Technical level'), ('some_college', 'College level'), ('bachelors', "Bachelor's Degree"), ('masters', "Master's Degree"), ('doctorate', 'Doctorate Degree/PhD'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fahaniecaresmember',
            name='sector',
            field=models.CharField(choices=[('pwd_student', 'PWD College Students'), ('solo_parent', 'Solo Parents'), ('volunteer_teacher', 'Volunteer Teachers'), ('volunteer_health', 'Volunteer Health Workers'), ('special_needs', 'Children with Special Needs'), ('women_mothers', 'Women/Mothers and Children'), ('student', 'Students in need of Scholarship/Financial Assistance')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fahaniecaresmember',
            name='voter_id_photo',
            field=models.ImageField(blank=True, help_text="Upload a clear photo of your Voter's Certificate or ID for verification.", null=True, upload_to=apps.constituents.utils.safe_voter_id_upload),
        ),
    ]
