# Generated by Django 4.2.22 on 2025-06-30 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constituents', '0006_alter_fahaniecaresmember_eligibility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fahaniecaresmember',
            name='eligibility',
            field=models.CharField(choices=[('none', 'None'), ('prc_passer', 'PRC Passer'), ('csc_passer', 'CSC Passer'), ('both', 'Both PRC and CSC Passer')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='fahaniecaresmember',
            name='sector',
            field=models.CharField(choices=[('pwd_student', 'Person with Disability (PWD)'), ('solo_parent', 'Solo Parents'), ('volunteer_teacher', 'Volunteer Teachers'), ('volunteer_health', 'Volunteer Health Workers'), ('special_needs', 'Children with Special Needs'), ('women_mothers', 'Women/Mothers and Children'), ('student', 'Students in need of Scholarship/Financial Assistance')], max_length=50),
        ),
    ]
