# Generated by Django 4.2.22 on 2025-07-03 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constituents', '0008_alter_constituent_occupation_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fahaniecaresmember',
            name='is_volunteer_teacher',
            field=models.BooleanField(default=False, verbose_name='Volunteer Teacher'),
        ),
    ]
