# Generated by Django 4.2.22 on 2025-07-03 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constituents', '0009_alter_fahaniecaresmember_is_volunteer_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fahaniecaresmember',
            name='is_volunteer_teacher',
        ),
        migrations.RemoveField(
            model_name='fahaniecaresmember',
            name='volunteer_school',
        ),
        migrations.RemoveField(
            model_name='fahaniecaresmember',
            name='volunteer_service_length',
        ),
        migrations.AlterField(
            model_name='fahaniecaresmember',
            name='sector',
            field=models.CharField(choices=[('pwd_student', 'Person with Disability (PWD)'), ('solo_parent', 'Solo Parents'), ('volunteer_health', 'Volunteer Health Workers'), ('special_needs', 'Children with Special Needs'), ('women_mothers', 'Women/Mothers and Children'), ('farmer', 'Farmers'), ('fisherman', 'Fishermen'), ('small_time_vendor', 'Small-time Vendors'), ('student', 'Students in need of Scholarship/Financial Assistance')], max_length=50),
        ),
    ]
