# Generated by Django 4.2.22 on 2025-07-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constituents', '0010_remove_fahaniecaresmember_is_volunteer_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fahaniecaresmember',
            name='member_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fahaniecaresmember',
            name='sector',
            field=models.CharField(choices=[('pwd_student', 'Person with Disability (PWD)'), ('solo_parent', 'Solo Parents'), ('volunteer_health', 'Volunteer Health Workers'), ('volunteer_teacher', 'Volunteer Teachers'), ('special_needs', 'Children with Special Needs'), ('women_mothers', 'Women/Mothers and Children'), ('farmer', 'Farmers'), ('fisherman', 'Fishermen'), ('small_time_vendor', 'Small-time Vendors'), ('student', 'Students in need of Scholarship/Financial Assistance')], max_length=50),
        ),
    ]
