# Generated by Django 4.2.22 on 2025-07-21 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('constituents', '0011_fahaniecaresmember_member_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fahaniecaresmember',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='fahaniecaresmember',
            name='denial_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fahaniecaresmember',
            name='denied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denied_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fahaniecaresmember',
            name='denied_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fahaniecaresmember',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('archived', 'Archived')], default='pending', max_length=10),
        ),
    ]
