# Generated by Django 4.2.22 on 2025-07-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constituents', '0012_remove_bmparliamentmember_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmparliamentmember',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('incomplete', 'Incomplete'), ('archived', 'Archived')], default='pending', max_length=10),
        ),
    ]
