# Generated by Django 4.2.22 on 2025-07-21 07:21

from django.db import migrations

def restore_approved_status(apps, schema_editor):
    FahanieCaresMember = apps.get_model('constituents', 'FahanieCaresMember')
    # Filter for members whose status is currently 'pending' but have a permanent member_id
    # This assumes that only previously approved members would have a non-temporary member_id
    # and that new pending registrants have a member_id starting with 'PREG'
    members_to_restore = FahanieCaresMember.objects.filter(
        status='pending'
    ).exclude(
        member_id__startswith='PREG'
    )
    
    for member in members_to_restore:
        member.status = 'approved'
        member.save(update_fields=['status']) # Save only the status field to avoid triggering other save logic

class Migration(migrations.Migration):

    dependencies = [
        ('constituents', '0013_update_member_statuses'),
    ]

    operations = [
        migrations.RunPython(restore_approved_status),
    ]
