# Generated by Django 4.2.22 on 2025-07-22 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constituents', '0014_restore_approved_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fahaniecaresmember',
            name='sector',
            field=models.CharField(choices=[('pwd_student', 'Person with Disability (PWD)'), ('solo_parent', 'Solo Parents'), ('volunteer_health', 'Volunteer Health Workers'), ('volunteer_teacher', 'Volunteer Teachers'), ('special_needs', 'Children with Special Needs'), ('women_mothers', 'Women/Mothers and Children'), ('farmer', 'Farmers'), ('fisherman', 'Fishermen'), ('small_time_vendor', 'Small-time Vendors'), ('dressmaker_weaver', 'Dressmaker/Weaver'), ('student', 'Students in need of Scholarship/Financial Assistance')], max_length=50),
        ),
    ]
