# Generated by Django 4.2.22 on 2025-11-03 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constituents', '0021_add_cancer_dialysis_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fahaniecaresmember',
            name='sector',
            field=models.CharField(choices=[('student', 'College Students in need of Educational Assistance'), ('delivery_riders', 'Delivery Riders'), ('dressmaker_weaver', 'Dressmaker/Weaver'), ('farmer', 'Farmers'), ('fisherman', 'Fishermen'), ('women_mothers', 'Learning Women/Mothers (Ummahat)'), ('lgbtq_community', 'LGBTQ+ Community Members'), ('madaris_students', 'Madaris Students'), ('mujahidin', 'Mujahidin/Mujahidat'), ('special_needs', 'Parents/Guardians of Children with Special Needs'), ('pwd_student', 'Person with Disability (PWD)'), ('volunteer_teacher', 'Public School Volunteer Teachers (English/Arabic)'), ('small_time_vendor', 'Small-time Vendors'), ('solo_parent', 'Solo Parents'), ('volunteer_health', 'Volunteer Health Workers'), ('cancer_dialysis', 'Cancer/Dialysis Patients')], max_length=50),
        ),
    ]
