# Generated by Django 4.2.22 on 2025-11-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constituents', '0023_rename_fahanie_cares_member_to_bm_parliament_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmparliamentmember',
            name='sector',
            field=models.CharField(choices=[('student', 'College Students in need of Educational Assistance'), ('delivery_riders', 'Delivery Riders'), ('dressmaker_weaver', 'Dressmaker/Weaver'), ('farmer', 'Farmers'), ('fisherman', 'Fishermen'), ('women_mothers', 'Learning Women/Mothers (Ummahat)'), ('madaris_students', 'Madaris Students'), ('mujahidin', 'Mujahidin/Mujahidat'), ('special_needs', 'Parents/Guardians of Children with Special Needs'), ('pwd_student', 'Person with Disability (PWD)'), ('volunteer_teacher', 'Public School Volunteer Teachers (English/Arabic)'), ('small_time_vendor', 'Small-time Vendors'), ('solo_parent', 'Solo Parents'), ('volunteer_health', 'Volunteer Health Workers'), ('cancer_dialysis', 'Hospital Patients')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bmparliamentmember',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=20),
        ),
        migrations.AlterField(
            model_name='constituent',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20),
        ),
    ]
