# Generated by Django 4.2.7 on 2025-06-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0003_service_is_featured'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='referraldocument',
            name='uploaded_by',
        ),
        migrations.AlterField(
            model_name='referral',
            name='supporting_documents',
            field=models.JSONField(blank=True, default=list, help_text='List of supporting documents provided'),
        ),
        migrations.AlterField(
            model_name='service',
            name='contact_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='eligibility_criteria',
            field=models.TextField(blank=True, help_text='Structured eligibility criteria', null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='required_documents',
            field=models.JSONField(blank=True, default=list, help_text='List of required documents'),
        ),
    ]
