# Generated by Django 4.2.7 on 2025-06-07 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0005_agency_contact_info_agency_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='notion_id',
        ),
        migrations.RemoveField(
            model_name='historicalagency',
            name='notion_id',
        ),
        migrations.RemoveField(
            model_name='historicalreferral',
            name='notion_id',
        ),
        migrations.RemoveField(
            model_name='historicalreferraldocument',
            name='notion_id',
        ),
        migrations.RemoveField(
            model_name='historicalreferralupdate',
            name='notion_id',
        ),
        migrations.RemoveField(
            model_name='historicalservice',
            name='notion_id',
        ),
        migrations.RemoveField(
            model_name='historicalservicecategory',
            name='notion_id',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='notion_id',
        ),
        migrations.RemoveField(
            model_name='referraldocument',
            name='notion_id',
        ),
        migrations.RemoveField(
            model_name='referralupdate',
            name='notion_id',
        ),
        migrations.RemoveField(
            model_name='service',
            name='notion_id',
        ),
        migrations.RemoveField(
            model_name='servicecategory',
            name='notion_id',
        ),
    ]
