"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.21.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-c3p*g=-@1&=5dq#9m-k=g06^u0x&lc6*aze%5vex)0+m4^g^j&')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', 'fahaniecares.ph,www.fahaniecares.ph,127.0.0.1').split(',')

# CSRF Configuration - Secure environment-conditional setup
CSRF_TRUSTED_ORIGINS = []

# Production domains (always included - secure HTTPS only)
PRODUCTION_DOMAINS = [
    'https://fahaniecares.ph',
    'https://www.fahaniecares.ph',
]
CSRF_TRUSTED_ORIGINS.extend(PRODUCTION_DOMAINS)

# Environment-specific additions
if DEBUG:  # Development/testing only
    DEVELOPMENT_DOMAINS = [
        'http://localhost:3000',
        'http://127.0.0.1:3000',
        'http://localhost:8000', 
        'http://127.0.0.1:8000',
        'http://fahaniecares.ph',      # For local testing with production domain
        'http://www.fahaniecares.ph'   # For local testing with production domain
    ]
    CSRF_TRUSTED_ORIGINS.extend(DEVELOPMENT_DOMAINS)

# Railway domains (validated for security)
RAILWAY_DOMAIN = os.environ.get('RAILWAY_PUBLIC_DOMAIN')
if RAILWAY_DOMAIN and RAILWAY_DOMAIN.endswith('.railway.app'):
    CSRF_TRUSTED_ORIGINS.append(f'https://{RAILWAY_DOMAIN}')
    if DEBUG:  # Allow HTTP in development only
        CSRF_TRUSTED_ORIGINS.append(f'http://{RAILWAY_DOMAIN}')

# Allow environment override (with validation)
CUSTOM_CSRF_ORIGINS = os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '')
if CUSTOM_CSRF_ORIGINS:
    custom_origins = [origin.strip() for origin in CUSTOM_CSRF_ORIGINS.split(',') if origin.strip()]
    # In production, only allow HTTPS origins from environment override
    if not DEBUG:
        custom_origins = [origin for origin in custom_origins if origin.startswith('https://')]
    CSRF_TRUSTED_ORIGINS.extend(custom_origins)

# Remove duplicates while preserving order
CSRF_TRUSTED_ORIGINS = list(dict.fromkeys(CSRF_TRUSTED_ORIGINS))

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize', # Required for intcomma filter
    'apps.users',
    'apps.chapters',
    'apps.communications',
    'apps.constituents',
    'apps.dashboards',
    'apps.documents',
    'apps.notifications',
    'apps.parliamentary',
    'apps.referrals',
    'apps.search',
    'apps.services',
    'apps.core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'apps.users.security.SecurityHeadersMiddleware',
    'apps.users.security.RateLimitMiddleware',
    'apps.users.security.MFAMiddleware',
    'apps.users.security.SessionSecurityMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'fahanie_cares_dev',
        'USER': 'fariss',
        'PASSWORD': 'glimpse2964',
        'HOST': '127.0.0.1',
        'PORT': '5432',
        'OPTIONS': {'options': '-c search_path=public'},
    }
}

print("DEBUG: settings.py is being loaded.")
print(f"DEBUG: BASE_DIR: {BASE_DIR}")
print(f"DEBUG: STATICFILES_DIRS: {STATICFILES_DIRS}")
print(f"DEBUG: DATABASES setting: {DATABASES}")


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CSRF and Session Cookie Security
# Set to True in production when using HTTPS
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG

# Prevent client-side JavaScript access to CSRF and Session cookies
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_HTTPONLY = True

# Optional: Set CSRF_COOKIE_DOMAIN if you have specific domain requirements (e.g., subdomains)
# CSRF_COOKIE_DOMAIN = '.fahaniecares.ph' # Example for a domain and its subdomains

# Trust X-Forwarded-Proto header from reverse proxy for HTTPS detection
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
