# Generated by Django 4.2 on 2025-05-18 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, unique=True)),
                ('frequency', models.IntegerField(default=1)),
                ('module', models.CharField(blank=True, max_length=50)),
                ('last_used', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-frequency', '-last_used'],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.CharField(max_length=500)),
                ('module', models.CharField(choices=[('all', 'All'), ('constituents', 'Constituents'), ('referrals', 'Referrals'), ('chapters', 'Chapters'), ('services', 'Services'), ('documents', 'Documents'), ('parliamentary', 'Parliamentary')], max_length=50)),
                ('filters', models.JSONField(default=dict)),
                ('result_count', models.IntegerField(default=0)),
                ('search_duration', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('query', models.CharField(blank=True, max_length=500)),
                ('filters', models.JSONField(default=dict)),
                ('module', models.CharField(choices=[('all', 'All'), ('constituents', 'Constituents'), ('referrals', 'Referrals'), ('chapters', 'Chapters'), ('services', 'Services'), ('documents', 'Documents'), ('parliamentary', 'Parliamentary')], max_length=50)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('use_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_used'],
            },
        ),
    ]
