# Generated by Django 4.2.7 on 2025-05-27 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinistryProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique ministry program code', max_length=50, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('ministry', models.CharField(choices=[('mssd', 'Ministry of Social Services and Development'), ('mafar', 'Ministry of Agriculture, Fisheries and Agrarian Reform'), ('mtit', 'Ministry of Trade, Industry and Tourism'), ('mhe', 'Ministry of Higher Education'), ('mbasiced', 'Ministry of Basic, Higher and Technical Education'), ('moh', 'Ministry of Health'), ('mpwh', 'Ministry of Public Works and Highways'), ('motc', 'Ministry of Transportation and Communications'), ('mei', 'Ministry of Environment and Interior'), ('mle', 'Ministry of Labor and Employment'), ('other', 'Other Ministry/Office')], max_length=20)),
                ('ppa_type', models.CharField(choices=[('program', 'Program'), ('project', 'Project'), ('activity', 'Activity')], max_length=20)),
                ('description', models.TextField(help_text='Comprehensive program description')),
                ('objectives', models.TextField(help_text='Program objectives and goals')),
                ('expected_outcomes', models.TextField(help_text='Expected outcomes and impacts')),
                ('key_performance_indicators', models.TextField(help_text='KPIs for monitoring and evaluation')),
                ('target_beneficiaries', models.TextField(help_text='Description of target beneficiaries')),
                ('geographic_coverage', models.TextField(help_text='Geographic areas covered')),
                ('estimated_beneficiaries', models.PositiveIntegerField(default=0)),
                ('implementation_strategy', models.TextField(help_text='How the program will be implemented')),
                ('implementing_units', models.TextField(help_text='Responsible implementing units/offices')),
                ('partner_agencies', models.TextField(blank=True, help_text='Partner agencies and organizations')),
                ('total_budget', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('allocated_budget', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('utilized_budget', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('funding_source', models.CharField(choices=[('national', 'National Government'), ('regional', 'Regional Government (BARMM)'), ('local', 'Local Government Unit'), ('international', 'International Donor'), ('private', 'Private Sector'), ('mixed', 'Mixed Sources')], max_length=20)),
                ('funding_details', models.TextField(blank=True, help_text='Detailed funding information')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration_months', models.PositiveIntegerField(help_text='Program duration in months')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('active', 'Active'), ('suspended', 'Suspended'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('priority_level', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('is_public', models.BooleanField(default=True, help_text='Whether program is visible to public')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured program on homepage')),
                ('requires_approval', models.BooleanField(default=True, help_text='Changes require approval')),
                ('program_document', models.FileField(blank=True, null=True, upload_to='ministry_programs/documents/')),
                ('implementation_guidelines', models.FileField(blank=True, null=True, upload_to='ministry_programs/guidelines/')),
                ('monitoring_framework', models.FileField(blank=True, null=True, upload_to='ministry_programs/monitoring/')),
                ('notion_database_id', models.CharField(blank=True, help_text='Notion database ID', max_length=36)),
                ('external_system_id', models.CharField(blank=True, help_text='External system reference', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deletion_reason', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_programs', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_ministry_programs', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_programs', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_modified_programs', to=settings.AUTH_USER_MODEL)),
                ('ministry_liaison', models.ForeignKey(blank=True, help_text='Ministry liaison officer responsible for this program', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liaised_programs', to=settings.AUTH_USER_MODEL)),
                ('program_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'ministry', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MinistryProgramHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('restore', 'Restored'), ('approve', 'Approved'), ('suspend', 'Suspended'), ('complete', 'Completed')], max_length=20)),
                ('changed_fields', models.JSONField(default=dict, help_text='Fields that were changed')),
                ('old_values', models.JSONField(default=dict, help_text='Previous values')),
                ('new_values', models.JSONField(default=dict, help_text='New values')),
                ('reason', models.TextField(blank=True, help_text='Reason for the change')),
                ('comments', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='program_changes', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='services.ministryprogram')),
            ],
            options={
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['program', 'changed_at'], name='services_mi_program_13a4b0_idx'), models.Index(fields=['action_type', 'changed_at'], name='services_mi_action__fe46eb_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='ministryprogram',
            index=models.Index(fields=['ministry', 'status'], name='services_mi_ministr_627de2_idx'),
        ),
        migrations.AddIndex(
            model_name='ministryprogram',
            index=models.Index(fields=['status', 'is_deleted'], name='services_mi_status_44e884_idx'),
        ),
        migrations.AddIndex(
            model_name='ministryprogram',
            index=models.Index(fields=['created_at'], name='services_mi_created_ed9abd_idx'),
        ),
    ]
