# Generated by Django 4.2.7 on 2025-06-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_historicalserviceapplication_applicant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministryprogram',
            name='program_source',
            field=models.CharField(choices=[('ministry', 'Ministry Program'), ('fahaniecares', '#FahanieCares Program'), ('tdif_infra', 'TDIF Infrastructure Project'), ('tdif_non_infra', 'TDIF Non-Infrastructure Project')], default='ministry', help_text='Source/category of this program', max_length=20),
        ),
    ]
