# Generated by Django 4.2.7 on 2025-06-07 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_simplify_program_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceapplication',
            name='notion_id',
        ),
        migrations.RemoveField(
            model_name='serviceprogram',
            name='notion_id',
        ),
    ]
