# Generated by Django 4.2.22 on 2025-06-25 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('constituents', '0006_alter_fahaniecaresmember_eligibility_and_more'),
        ('services', '0008_applicationattachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceapplication',
            options={'ordering': ['-application_date']},
        ),
        migrations.AlterModelOptions(
            name='servicedisbursement',
            options={'ordering': ['-scheduled_date', '-created_at']},
        ),
        migrations.RenameField(
            model_name='serviceapplication',
            old_name='created_at',
            new_name='application_date',
        ),
        migrations.RenameField(
            model_name='serviceimpact',
            old_name='challenges_faced',
            new_name='challenges',
        ),
        migrations.AlterUniqueTogether(
            name='serviceapplication',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='servicedisbursement',
            name='processed_by',
        ),
        migrations.RemoveField(
            model_name='servicedisbursement',
            name='receipt',
        ),
        migrations.RemoveField(
            model_name='servicedisbursement',
            name='recipient_id_number',
        ),
        migrations.RemoveField(
            model_name='servicedisbursement',
            name='recipient_id_type',
        ),
        migrations.RemoveField(
            model_name='servicedisbursement',
            name='recipient_name',
        ),
        migrations.RemoveField(
            model_name='servicedisbursement',
            name='supporting_docs',
        ),
        migrations.RemoveField(
            model_name='serviceimpact',
            name='average_assistance',
        ),
        migrations.RemoveField(
            model_name='serviceimpact',
            name='barangays_served',
        ),
        migrations.RemoveField(
            model_name='serviceimpact',
            name='detailed_report',
        ),
        migrations.RemoveField(
            model_name='serviceimpact',
            name='direct_beneficiaries',
        ),
        migrations.RemoveField(
            model_name='serviceimpact',
            name='impact_photos',
        ),
        migrations.RemoveField(
            model_name='serviceimpact',
            name='indirect_beneficiaries',
        ),
        migrations.RemoveField(
            model_name='serviceimpact',
            name='municipalities_served',
        ),
        migrations.RemoveField(
            model_name='serviceimpact',
            name='prepared_by',
        ),
        migrations.RemoveField(
            model_name='serviceimpact',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='serviceimpact',
            name='success_stories',
        ),
        migrations.RemoveField(
            model_name='serviceimpact',
            name='total_disbursed',
        ),
        migrations.AddField(
            model_name='serviceapplication',
            name='constituent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service_applications', to='constituents.constituent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceapplication',
            name='remarks',
            field=models.TextField(blank=True, help_text='Internal remarks about the application'),
        ),
        migrations.AddField(
            model_name='servicedisbursement',
            name='disbursed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursements_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceimpact',
            name='qualitative_impact',
            field=models.TextField(blank=True, help_text='Narrative description of impact'),
        ),
        migrations.AddField(
            model_name='serviceimpact',
            name='quantitative_data',
            field=models.JSONField(blank=True, default=dict, help_text="JSON field for structured data (e.g., {'jobs_created': 10, 'literacy_rate_increase': 0.15})", null=True),
        ),
        migrations.AddField(
            model_name='serviceimpact',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impact_reports_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='serviceapplication',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='serviceapplication',
            name='assessment_notes',
            field=models.TextField(blank=True, help_text='Notes from the application assessment'),
        ),
        migrations.AlterField(
            model_name='serviceapplication',
            name='assistance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='serviceapplication',
            name='assistance_description',
            field=models.TextField(blank=True, help_text='Description of assistance provided'),
        ),
        migrations.AlterField(
            model_name='serviceapplication',
            name='beneficiary_contact',
            field=models.CharField(blank=True, help_text='Contact number of the beneficiary', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceapplication',
            name='beneficiary_is_self',
            field=models.BooleanField(default=True, help_text='Is the beneficiary the same as the applicant?'),
        ),
        migrations.AlterField(
            model_name='serviceapplication',
            name='beneficiary_name',
            field=models.CharField(blank=True, help_text='Full name of the beneficiary if different from applicant', max_length=255),
        ),
        migrations.AlterField(
            model_name='serviceapplication',
            name='beneficiary_relationship',
            field=models.CharField(blank=True, help_text='Relationship of beneficiary to applicant', max_length=100),
        ),
        migrations.AlterField(
            model_name='serviceapplication',
            name='disbursement_method',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceapplication',
            name='home_visit_report',
            field=models.TextField(blank=True, help_text='Report from home visit, if conducted'),
        ),
        migrations.AlterField(
            model_name='serviceapplication',
            name='household_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='serviceapplication',
            name='household_size',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='serviceapplication',
            name='priority_level',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='serviceapplication',
            name='reason_for_application',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='serviceapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='serviceapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicedisbursement',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='servicedisbursement',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('voucher', 'Voucher'), ('in_kind', 'In-Kind')], max_length=20),
        ),
        migrations.AlterField(
            model_name='servicedisbursement',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Transaction or reference number', max_length=100),
        ),
        migrations.AlterField(
            model_name='servicedisbursement',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('disbursed', 'Disbursed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceimpact',
            name='report_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='serviceapplication',
            unique_together={('program', 'constituent')},
        ),
        migrations.RemoveField(
            model_name='serviceapplication',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='serviceapplication',
            name='application_number',
        ),
        migrations.RemoveField(
            model_name='serviceapplication',
            name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='serviceapplication',
            name='supporting_documents',
        ),
        migrations.RemoveField(
            model_name='serviceapplication',
            name='updated_at',
        ),
    ]
