# Generated by Django 4.2.22 on 2025-06-26 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_serviceapplication_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='serviceapplication',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='serviceapplication',
            name='ministry_program',
            field=models.ForeignKey(blank=True, help_text='The ministry program applied for (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='services.ministryprogram'),
        ),
        migrations.AddField(
            model_name='serviceapplication',
            name='service_program',
            field=models.ForeignKey(blank=True, help_text='The service program applied for (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='services.serviceprogram'),
        ),
        migrations.RemoveField(
            model_name='serviceapplication',
            name='program',
        ),
    ]
