# Generated by Django 4.2.22 on 2025-06-26 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constituents', '0006_alter_fahaniecaresmember_eligibility_and_more'),
        ('services', '0010_alter_serviceapplication_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceapplication',
            name='constituent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_applications', to='constituents.fahaniecaresmember'),
        ),
    ]
