# Generated by Django 4.2.22 on 2025-06-30 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_alter_serviceapplication_constituent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministryprogram',
            name='funding_source',
            field=models.CharField(choices=[('national', 'National Government'), ('regional', 'Regional Government (BARMM)'), ('local', 'Local Government Unit'), ('international', 'International Donor'), ('private', 'Private Sector'), ('mixed', 'Mixed Sources'), ('office_mooe', 'Office MOOE'), ('implementing_ministry', 'Implementing Ministry')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ministryprogram',
            name='ministry',
            field=models.CharField(choices=[('mssd', 'Ministry of Social Services and Development'), ('mafar', 'Ministry of Agriculture, Fisheries and Agrarian Reform'), ('mtit', 'Ministry of Trade, Industry and Tourism'), ('mhe', 'Ministry of Higher Education'), ('mbasiced', 'Ministry of Basic, Higher and Technical Education'), ('moh', 'Ministry of Health'), ('mpwh', 'Ministry of Public Works and Highways'), ('motc', 'Ministry of Transportation and Communications'), ('mei', 'Ministry of Environment and Interior'), ('mle', 'Ministry of Labor and Employment'), ('mp_office', 'Office of MP Atty. Sittie Fahanie S. Uy-Oyod'), ('other', 'Other Ministry/Office')], max_length=20),
        ),
    ]
