# Generated by Django 4.2.22 on 2025-07-11 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_alter_ministryprogram_funding_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministryprogram',
            name='duration_months',
            field=models.PositiveIntegerField(blank=True, help_text='Program duration in months', null=True),
        ),
        migrations.AlterField(
            model_name='serviceprogram',
            name='program_type',
            field=models.CharField(choices=[('educational', 'Educational Support'), ('health', 'Healthcare Services'), ('livelihood', 'Livelihood Assistance'), ('emergency', 'Emergency Relief'), ('infrastructure', 'Community Infrastructure'), ('social', 'Social Services'), ('youth', 'Youth Development'), ('elderly', 'Senior Citizen Support'), ('pwd', 'PWD Assistance'), ('volunteer_teachers', 'Volunteer Teachers'), ('other', 'Other Services')], max_length=20),
        ),
    ]
