# Generated by Django 4.2.22 on 2025-10-08 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('constituents', '0020_add_lgbtq_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('database_type', models.CharField(choices=[('attendance', 'Attendance Database'), ('events', 'Events Database'), ('training', 'Training Programs Database'), ('volunteers', 'Volunteer Activities Database'), ('beneficiaries', 'Beneficiaries Database'), ('custom', 'Custom Database')], default='custom', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False, help_text='Allow public access to this database')),
                ('allow_self_registration', models.BooleanField(default=False, help_text='Allow users to add themselves')),
                ('allowed_roles', models.JSONField(default=list, help_text='List of user roles that can access this database. Empty list means all roles.')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_users', models.ManyToManyField(blank=True, help_text='Specific users with access to this database', related_name='accessible_databases', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_databases', to=settings.AUTH_USER_MODEL)),
                ('parent_database', models.ForeignKey(blank=True, help_text='Parent database for hierarchical structure', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_databases', to='unified_db.generaldatabase')),
            ],
            options={
                'verbose_name': 'General Database',
                'verbose_name_plural': 'General Databases',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DatabaseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_first_name', models.CharField(blank=True, max_length=100)),
                ('guest_last_name', models.CharField(blank=True, max_length=100)),
                ('guest_middle_name', models.CharField(blank=True, max_length=100)),
                ('guest_email', models.EmailField(blank=True, max_length=254)),
                ('guest_phone', models.CharField(blank=True, max_length=20)),
                ('entry_data', models.JSONField(default=dict, help_text='Flexible storage for all field values')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search_text', models.TextField(blank=True, help_text='Concatenated searchable text')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_entries', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_entries', to=settings.AUTH_USER_MODEL)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='unified_db.generaldatabase')),
                ('linked_user', models.ForeignKey(blank=True, help_text='Link to existing user account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='database_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Database Entry',
                'verbose_name_plural': 'Database Entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_name', models.CharField(help_text='Primary name for this person', max_length=255)),
                ('normalized_name', models.CharField(help_text='Normalized name for matching', max_length=255)),
                ('external_id', models.CharField(blank=True, help_text='ID in external system', max_length=100)),
                ('external_system', models.CharField(blank=True, help_text='Name of external system', max_length=100)),
                ('confidence_score', models.FloatField(default=1.0, help_text='Confidence in person matching (0-1)')),
                ('is_verified', models.BooleanField(default=False, help_text='Manually verified match')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('constituent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_links', to='constituents.constituent')),
                ('database_entries', models.ManyToManyField(blank=True, related_name='person_links', to='unified_db.databaseentry')),
                ('fahanie_cares_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_links', to='constituents.fahaniecaresmember')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_person_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Person Link',
                'verbose_name_plural': 'Person Links',
                'ordering': ['-confidence_score', '-created_at'],
                'indexes': [models.Index(fields=['normalized_name'], name='unified_db__normali_3fbf2c_idx'), models.Index(fields=['primary_name'], name='unified_db__primary_972617_idx'), models.Index(fields=['confidence_score'], name='unified_db__confide_44f491_idx')],
            },
        ),
        migrations.CreateModel(
            name='DatabaseField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(help_text='Display label for the field', max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text Input'), ('textarea', 'Text Area'), ('number', 'Number'), ('email', 'Email'), ('phone', 'Phone Number'), ('date', 'Date'), ('datetime', 'Date & Time'), ('select', 'Select Dropdown'), ('multiselect', 'Multiple Select'), ('checkbox', 'Checkbox'), ('radio', 'Radio Buttons'), ('file', 'File Upload'), ('image', 'Image Upload'), ('url', 'URL'), ('hidden', 'Hidden Field')], max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('is_searchable', models.BooleanField(default=True, help_text='Include in search results')),
                ('is_filterable', models.BooleanField(default=False, help_text='Show as filter option')),
                ('default_value', models.CharField(blank=True, max_length=500)),
                ('placeholder', models.CharField(blank=True, max_length=255)),
                ('help_text', models.TextField(blank=True)),
                ('options', models.JSONField(default=list, help_text="List of options for select fields. Format: [{'value': 'opt1', 'label': 'Option 1'}]")),
                ('validation_type', models.CharField(choices=[('none', 'No Validation'), ('required', 'Required Field'), ('email', 'Valid Email'), ('phone', 'Valid Phone Number'), ('numeric', 'Numeric Only'), ('min_length', 'Minimum Length'), ('max_length', 'Maximum Length'), ('min_value', 'Minimum Value'), ('max_value', 'Maximum Value'), ('regex', 'Regular Expression')], default='none', max_length=20)),
                ('validation_rules', models.JSONField(default=dict, help_text='Validation parameters (min_length, max_length, regex pattern, etc.)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='unified_db.generaldatabase')),
            ],
            options={
                'verbose_name': 'Database Field',
                'verbose_name_plural': 'Database Fields',
                'ordering': ['order', 'name'],
                'unique_together': {('database', 'name')},
            },
        ),
        migrations.AddIndex(
            model_name='databaseentry',
            index=models.Index(fields=['database', 'status'], name='unified_db__databas_550524_idx'),
        ),
        migrations.AddIndex(
            model_name='databaseentry',
            index=models.Index(fields=['linked_user'], name='unified_db__linked__23b11b_idx'),
        ),
        migrations.AddIndex(
            model_name='databaseentry',
            index=models.Index(fields=['guest_email'], name='unified_db__guest_e_918546_idx'),
        ),
        migrations.AddIndex(
            model_name='databaseentry',
            index=models.Index(fields=['guest_first_name', 'guest_last_name'], name='unified_db__guest_f_51e1ad_idx'),
        ),
    ]
