# Generated by Django 4.2 on 2025-05-18 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('attended', 'Attended'), ('absent', 'Absent'), ('cancelled', 'Cancelled')], default='registered', max_length=20)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('volunteer_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tasks_completed', models.TextField(blank=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['activity', 'attendee'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('tier', models.CharField(choices=[('provincial', 'Provincial Chapter'), ('municipal', 'Municipal Chapter'), ('barangay', 'Barangay Chapter'), ('overseas', 'Overseas Chapter')], max_length=20)),
                ('municipality', models.CharField(max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Philippines', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('mission_statement', models.TextField(blank=True)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending Approval'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('meeting_location', models.TextField(blank=True)),
                ('meeting_schedule', models.CharField(blank=True, max_length=200)),
                ('facebook_page', models.URLField(blank=True)),
                ('twitter_handle', models.CharField(blank=True, max_length=50)),
                ('instagram_handle', models.CharField(blank=True, max_length=50)),
                ('member_count', models.PositiveIntegerField(default=0)),
                ('volunteer_count', models.PositiveIntegerField(default=0)),
                ('activity_count', models.PositiveIntegerField(default=0)),
                ('notion_id', models.CharField(blank=True, help_text='Notion database ID', max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapters_approved', to=settings.AUTH_USER_MODEL)),
                ('assistant_coordinators', models.ManyToManyField(blank=True, related_name='assistant_coordinated_chapters', to=settings.AUTH_USER_MODEL)),
                ('coordinator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_chapters', to=settings.AUTH_USER_MODEL)),
                ('parent_chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_chapters', to='chapters.chapter')),
            ],
            options={
                'verbose_name': 'Chapter',
                'verbose_name_plural': 'Chapters',
                'ordering': ['tier', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChapterActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('activity_type', models.CharField(choices=[('meeting', 'Regular Meeting'), ('outreach', 'Community Outreach'), ('fundraising', 'Fundraising Event'), ('training', 'Training/Workshop'), ('social', 'Social Gathering'), ('volunteer', 'Volunteer Activity'), ('campaign', 'Campaign Event'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('objectives', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='planned', max_length=20)),
                ('venue', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('online_link', models.URLField(blank=True, help_text='For virtual activities')),
                ('target_participants', models.PositiveIntegerField(default=0)),
                ('actual_participants', models.PositiveIntegerField(default=0)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('resources_needed', models.TextField(blank=True)),
                ('report', models.TextField(blank=True)),
                ('photos', models.FileField(blank=True, null=True, upload_to='chapter_activities/')),
                ('materials', models.FileField(blank=True, null=True, upload_to='chapter_materials/')),
                ('notion_id', models.CharField(blank=True, help_text='Notion database ID', max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='chapters.chapter')),
                ('co_organizers', models.ManyToManyField(blank=True, related_name='co_organized_activities', to=settings.AUTH_USER_MODEL)),
                ('member_attendees', models.ManyToManyField(related_name='attended_activities', through='chapters.ActivityAttendance', to=settings.AUTH_USER_MODEL)),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chapter Activity',
                'verbose_name_plural': 'Chapter Activities',
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.AddField(
            model_name='activityattendance',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='chapters.chapteractivity'),
        ),
        migrations.AddField(
            model_name='activityattendance',
            name='attendee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ChapterMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Member'), ('volunteer', 'Volunteer'), ('coordinator', 'Coordinator'), ('assistant_coordinator', 'Assistant Coordinator'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('auditor', 'Auditor'), ('committee_member', 'Committee Member')], default='member', max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('pending', 'Pending Approval')], default='pending', max_length=20)),
                ('joined_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('membership_number', models.CharField(blank=True, max_length=50)),
                ('is_volunteer', models.BooleanField(default=False)),
                ('volunteer_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('volunteer_skills', models.TextField(blank=True)),
                ('availability', models.CharField(blank=True, max_length=200)),
                ('committees', models.TextField(blank=True, help_text='Comma-separated list of committees')),
                ('activities_attended', models.PositiveIntegerField(default=0)),
                ('activities_organized', models.PositiveIntegerField(default=0)),
                ('referrals_made', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships_approved', to=settings.AUTH_USER_MODEL)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='chapters.chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joined_date'],
                'unique_together': {('chapter', 'user')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='activityattendance',
            unique_together={('activity', 'attendee')},
        ),
    ]
