# Generated by Django 4.2.7 on 2025-05-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0002_alter_chapter_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='tier',
            field=models.CharField(choices=[('provincial', 'Provincial Chapter'), ('municipal', 'Municipal/City Chapter')], max_length=20),
        ),
    ]
