# Generated by Django 4.2.7 on 2025-06-07 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0003_alter_chapter_tier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='notion_id',
        ),
        migrations.RemoveField(
            model_name='chapteractivity',
            name='notion_id',
        ),
    ]
